name: plant-disease-classification
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env: 
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.ORIGINAL_SERVICE_ACCOUNT_JSON }}
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote --local gdrive_use_service_account true
          dvc remote modify myremote --local gdrive_service_account_json_file_path /dev/null
          dvc remote list 

          dvc pull dataset --run-cache
          dvc repro          

          python train.py nn_config.yml

          echo "## Model metrics" > report.md
          # cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml-publish acc_per_epoch.png --md >> report.md
          cml-publish loss_per_epoch.png --md >> report.md

          cml-send-comment report.md
