name: plant-disease-classification
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
#           GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CREDENTIALS_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          
        run: |
          pip install -r requirements.txt

          # dvc remote modify myremote gdrive_client_id "$client_id"
          # dvc remote modify myremote gdrive_client_secret "$client_secret"

          dvc pull --run-cache
          python train.py nn_config.yml

          echo "## Model metrics" > report.md
          # cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml-publish acc_per_epoch.png --md >> report.md
          cml-publish loss_per_epoch.png --md >> report.md

          cml-send-comment report.md
