name: plant-disease-classification
on: [push]
jobs:
  steps:
    run:
      runs-on: [ubuntu-latest]
      container: docker://dvcorg/cml-py3:latest
      steps:
        - uses: actions/checkout@v2
        - name: cml_run
          env:
            repo_token: ${{ secrets.REPO_TOKEN }}
            GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          run: |

            pip install -r requirements.txt

            dvc pull  
            python train.py

            echo "## Model metrics" > report.md
            # cat metrics.txt >> report.md

            echo "## Data viz" >> report.md
            cml-publish acc_per_epoch.png --md >> report.md
            cml-publish loss_per_epoch.png --md >> report.md

            cml-send-comment report.md
