name: plant-disease-classification
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.8'
      #     cache: 'pip' # caching pip dependencies
      - name: Train fcn
        env: 
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.ORIGINAL_SERVICE_ACCOUNT_JSON }}
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          python --version
          pip install -r requirements.txt

          dvc remote modify myremote gdrive_acknowledge_abuse true
          dvc remote modify myremote gdrive_client_id ${{ secrets.GDRIVE_CLIENT_ID }}
          dvc remote modify myremote gdrive_client_secret ${{ secrets.GDRIVE_CLIENT_SECRET }}
          dvc --version

          dvc pull -r myremote
          dvc repro          

          python train.py nn_config.yml

          echo "## Model metrics" > report.md
          # cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml-publish acc_per_epoch.png --md >> report.md
          cml-publish loss_per_epoch.png --md >> report.md

          cml-send-comment report.md
