name: plant-disease-classification
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.8'
      #     cache: 'pip' # caching pip dependencies
      - name: Install packages

        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt      
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          python train.py nn_config.yml

          echo "## Model metrics" > report.md
          # cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml-publish acc_per_epoch.png --md >> report.md
          cml-publish loss_per_epoch.png --md >> report.md

          cml-send-comment report.md
