name: plant-disease-classification
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.8'
      #     cache: 'pip' # caching pip dependencies
      - name: Pull data
        env: 
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.ORIGINAL_SERVICE_ACCOUNT_JSON }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dvc remote modify myremote --local gdrive_use_service_account true
          dvc pull dataset --run-cache
          dvc repro          
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          python train.py nn_config.yml

          echo "## Model metrics" > report.md
          # cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml-publish acc_per_epoch.png --md >> report.md
          cml-publish loss_per_epoch.png --md >> report.md

          cml-send-comment report.md
