name: plant-disease-classification
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          gdrive_client_secret: ${{ secrets.GDRIVE_TOKEN}}
          gdrive_client_id: ${{ secrets.GDRIVE_ID }}
        
        run: |
          pip install -r requirements.txt
          
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote gdrive_client_secret $gdrive_client_secret
          dvc remote modify myremote gdrive_client_id $gdrive_client_id
          dvc pull --run-cache
          dvc repro

          python train.py

          echo "## Model metrics" > report.md
          # cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml-publish acc_per_epoch.png --md >> report.md
          cml-publish loss_per_epoch.png --md >> report.md

          cml-send-comment report.md
